# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

region: EU
vmpool:
  key:
    organization: GDDT
    name: automationVMPool
  vms:
  - name: automationvmpool1
    netinfo:
      externalip: 37.50.144.132
      internalip: 10.101.253.191
  - name: automationvmpool2
    netinfo:
      externalip: 37.50.144.181
      internalip: 10.101.253.192
  - name: automationvmpool3
    netinfo:
      externalip: 37.50.144.235
      internalip: 10.101.253.193
  - name: automationvmpool4
    netinfo:
      externalip: 37.50.144.149
      internalip: 10.101.253.194
  - name: automationvmpool5
    netinfo:
      externalip: 37.50.144.229
      internalip: 10.101.253.195
  - name: automationvmpool6
    netinfo:
      externalip: 37.50.144.188
      internalip: 10.101.253.196
